#tomacat相关配置
server:
  port: 9001
  tomcat:
    max-threads: 500 # Maximum amount of worker threads.
    min-spare-threads: 50 # Minimum amount of worker threads
#应用基本配置
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://cdb-d5ge3ujs.cd.tencentcdb.com:10003/auth??allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: y3tu46262966
    hikari:
      minimum-idle: 0
  #reids配置
  redis:
    host: 127.0.0.1
    port: 6379
    password:
  #rabbitmq配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  boot:
    admin:
      client:
        url: http://localhost:9006
        instance:
          service-base-url: http://localhost:9001
  cloud:
    sentinel:
      transport:
        port: 8720
        dashboard: localhost:8080
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        metadata:
          user.name: ${spring.security.user.name}
          user.password: ${spring.security.user.password}
  security:
    user:
      name: "y3tu"
      password: "admin"

#feign日志打印
logging:
  level:
    com.y3tu.cloud.auth.service.SysUserService: debug
#文件上传配置
#  http:
#    multipart:
#      max-file-size: 1000MB
#      max-request-size: 1000MB
ribbon:
  eager-load:
    enabled: true
    clients: back-service

feign:
  sentinel:
    enabled: true
  okhttp:
    enabled: false
  httpclient:
    enabled: true
  client:
    config:
      feignName:
        connectTimeout: 30000
        readTimeout: 30000
  compression:
    request:
      enabled: true
    response:
      enabled: true
#开启端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS