spring:
  datasource:
    #   数据源基本配置
    username: root
    password: ENC(cOR0AoFMGxjKtON7jQo1DVDTPC/qOvSF)
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://cdb-d5ge3ujs.cd.tencentcdb.com:10003/y3tu-admin??allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    #指定数据源
    type: com.alibaba.druid.pool.DruidDataSource

ignore:
  urls:
  - /actuator/**
  - /authentication/**
  - /**/*.css
  - /**/*.jpg
  - /**/*.png
  - /**/*.woff2
  - /**/*.js