server:
  port: 8443

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_ZONE_HOST:132.232.11.210}:${EUREKA_ZONE_PORT:8501}/eureka/

spring:
  profiles:
    active: dev
  application:
    name: y3tu-cloud-gateway-web
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: y3tu46262966
    url: jdbc:mysql://cdb-d5ge3ujs.cd.tencentcdb.com:10003/y3tu-admin??allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
  rabbitmq:
    host: ${RABBIT_MQ_HOST:132.232.11.210}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}
  redis:
    database: 0
    host: ${REDIS_HOST:132.232.11.210}
    port: ${REDIS_PORT:6379}
    password: yxy727      # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  security:
    oauth2:
      jwt:
        signingKey: 123456

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
      - AddResponseHeader=X-Response-Default-Foo, Default-Bar
      - name: RequestRateLimiter
        args:
          redis-rate-limiter.replenishRate: 1  #令牌桶的容积
          redis-rate-limiter.burstCapacity: 1  #流速 每秒
          rate-limiter: "#{@defaultRedisRateLimiter}"  #SPEL表达式去的对应的bean
          key-resolver: "#{@remoteAddressKeyResolver}" #SPEL表达式去的对应的bean
      routes:
      # =====================================
      - id: authorization-server
        uri: lb://authorization-server
        predicates:
        - Path=/authorization-server/**
        filters:
        - StripPrefix=1
        - AddResponseHeader=foo, bar


gate:
  ignore:
    authentication:
      startWith: /oauth,/open

management:
  endpoints:
    web:
      exposure:
        include: '*'

#请求和响应GZIP压缩支持
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    enabled: true

#  compression:
#    response:
#      enabled: true
#    request:
#      enabled: true
#      mime-types: text/xml,application/xml,application/json
#      min-request-size: 2048
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000

logging:
  level:
    com.y3tu.cloud.gateway: debug
    com.jalja.org.spring: debug
  path: logs/
  file:
    max-size: 1GB

