prod1:
  eureka:
    server:
      port: 8501
    hostname: 132.232.11.210
prod2:
  eureka:
    server:
      port: 8502
    hostname: y3tu2
dev:
  eureka:
    server:
      port: 8501
    hostname: localhost


# 公共配置
spring:
  profiles:
    active: dev
  application:
    name: y3tu-cloud-eureka
  security:
    user:
      name: y3tu
      password: ENC(CGwCeH7IWZgQMWjafiZt4w==)

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    servlet:
      context-path: /

info:
  artifact: y3tu-cloud-eureka
  name: '@project.name@'
  description: '@project.description@'
  version: '@project.version@'
  spring-boot-version: '@spring-boot.version@'
  spring-cloud-version: '@spring-cloud.version@'


jasypt:
  encryptor:
    password: 123456
