prod1:
  eureka:
    server:
      port: 8501
    hostname: 132.232.11.210
prod2:
  eureka:
    server:
      port: 8502
    hostname: y3tu2
dev:
  eureka:
    server:
      port: 8501
    hostname: localhost


# 公共配置
spring:
  profiles:
    active: dev
  application:
    name: y3tu-eureka

management:
  context-path: /actuator


info:
  artifact: y3tu-eureka
  name: '@project.name@'
  description: '@project.description@'
  version: '@project.version@'
  spring-boot-version: '@spring.boot.version@'
  spring-cloud-version: '@spring.cloud.version@'

