server:
  port: 5000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

turbine:
  aggregator:
    cluster-config: default
  app-config: authorization-server
  cluster-name-expression: new String("default")
