server:
  port: 9771

spring:
  redis:
    key-prefix: dev  # redis key的前缀， 环境的多个实例一定要配置一样（即prod1和prod2文件中需要配置一致）

logging:
  level:
    console: INFO
    filter: INFO

spring:
  rabbitmq:
    host: www.y3tu.com
    port: 5672
    username: y3tu
    password: 123456
    virtual-host: y3tu
  redis:
    host: www.y3tu.com
    port: 6379
  security:
      user:
        name: admin
        password: admin
# rabbitMQ/Mysql/Redis ip，端口，帐号等根据环境自行修改。


testConfig: y3tu...