prod1:
  eureka:
    server:
      port: 8501
    hostname: www.y3tu.com
prod2:
  eureka:
    server:
      port: 8502
    hostname: www.y3tu.com
dev:
  eureka:
    server:
      port: 8501
    hostname: www.y3tu.com

#日志配置
logging:
  path: ./logs/y3tu-config
  file: ${logging.path}/root.log
  common-pattern: '%d{yyyy-MM-dd HH:mm:ss.SSS}:[%5p] [%t:%r] [%C{1}:%M:%L] --> %m%n'
  level:
    console: INFO

#公共配置
spring:
  profiles:
    active: dev
  application:
    name: y3tu-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/y3tu/y3tu-cloud
          username: 14643092@qq.com
          password: ENC(dyXeseW+3pVFMpL89Xi4FHVdhpRLRJ9J)
          search-paths: y3tu-config-repo/*/{application}
  security:
    user:
      name: admin
      password: admin




#消息队列配置
rabbitmq:
    host: www.y3tu.com
    port: 5672
    password: admin
    username: admin

management:
  context-path: /actuator
  endpoints:
    web:
      exposure:
        include: "*" #配置actuator所有端点可访问



endpoints:
  health:
    enabled: true
    sensitive: true  # actuator的health接口是否需要安全保证


#jasypt加解密方式配置
jasypt:
  encryptor:
    password: y3tu #根密码


info:
  artifact: y3tu-config
  name: '@project.name@'
  description: '@project.description@'
  version: '@project.version@'
  spring-boot-version: '@spring-boot.version@'
  spring-cloud-version: '@spring-cloud.version@'



