prod1:
  eureka:
    server:
      port: 8501
    hostname: 132.232.11.210
prod2:
  eureka:
    server:
      port: 8502
    hostname: 132.232.11.210
dev:
  eureka:
    server:
      port: 8501
    hostname: localhost

#日志配置
logging:
  path: ./logs/y3tu-cloud-config
  file: ${logging.path}/root.log
  level:
    console: INFO

#公共配置
spring:
  profiles:
    active: dev
  application:
    name: y3tu-cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/y3tu/y3tu-cloud
          username: 14643092@qq.com
          password: ENC(lNPKGPdaXeoFmazawLAra85clN7/rSrO)
          search-paths: y3tu-config-repo/*/{application}
  security:
    user:
      name: y3tu
      password: ENC(CGwCeH7IWZgQMWjafiZt4w==)
  #消息队列配置
  rabbitmq:
    host: ${RABBIT_MQ_HOST:132.232.11.210}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*" #配置actuator所有端点可访问
  server:
    servlet:
      context-path: /


#jasypt加解密方式配置
jasypt:
  encryptor:
    password: 123456 #根密码


info:
  artifact: y3tu-cloud-config
  name: '@project.name@'
  description: '@project.description@'
  version: '@project.version@'
  spring-boot-version: '@spring-boot.version@'
  spring-cloud-version: '@spring-cloud.version@'



